### ISSUE TITLE
Unix collector panics when harvest.yml is changed

### ISSUE THREAD

**Issue by cgrinds** [NetApp/harvest#160]
Commit `7a0a026`

_Scripts to reproduce are below._

Every time the unix poller's `PollInstance` method is called, it rereads the list of pollers from the harvest config file. 

Rereading the file, means poller additions and deletions need to be correctly handled. They mostly are, except when you modify the name of an existing poller. Doesn't matter if that poller is started or not, just if the name changes.

Imagine there are three pollers:
- poller1 with a unix collector
- poller2 collector doesn't matter
- poller3 collector doesn't matter

You start `poller1` and a few minutes later rename `poller3` to `pollerC`.

The next time the unix collector runs, it will notice the change and adjust its matrix instances like so:

```
1	copy := clone of matrix instances
2	for pollerName in pollers from config:
3	    if matrix has pollerName:
4	        remove from copy
5	    else
6	        add new instance to matrix
7	for name in copy:
8	    remove name from matrix
```

In the case, of renaming `poller3`, the index of the renamed poller added at line 6 is wrong and at runtime we run off the end of the slice. Boom.

Indexes before rename:

```
poller1 has index 0
poller2 has index 1
poller3 has index 2
```

Indexes after rename:

```
poller1 has index 0
poller2 has index 1
pollerC has index 3
```

Adding the new instance at line 6 causes `pollerC` to have index 3 since it is the matrix's fourth poller. That's incorrect.
Indexes are immutable so the fix is to detect gaps and rewrite the matrix instances.

<details>
  <summary>Panic - click to expand</summary>

### Panic

4:43PM ERR goharvest2/cmd/poller/collector/collector.go:240 > Collector panicked error="goroutine panic => goroutine 11 [running]:\nruntime/debug.Stack(0xc00006cf60, 0x984403, 0x0)\n\truntime/debug/stack.go:24 +0x9f\ngoharvest2/cmd/poller/collector.(*AbstractCollector).Start.func1(0xc00009a370)\n\tgoharvest2/cmd/poller/collector/collector.go:240 +0x9d\npanic(0x984460, 0xc0003660a8)\n\truntime/panic.go:965 +0x1b9\ngoharvest2/pkg/matrix.(*MetricUint8).SetValueUint8(0xc0001ab200, 0xc0001e6cf0, 0x9bd401, 0x6, 0xc0001ba848)\n\tgoharvest2/pkg/matrix/metric_uint8.go:80 +0x1d2\ngoharvest2/pkg/matrix.(*Matrix).LazySetValueUint8(0xc00006e910, 0x9bd464, 0x6, 0xc0002c91f0, 0xf, 0x1, 0x9, 0xc0000bf990)\n\tgoharvest2/pkg/matrix/lazy.go:80 +0x310\ngoharvest2/cmd/collectors/unix.(*Unix).PollData(0xc000068e20, 0x0, 0x0, 0x0)\n\tgoharvest2/cmd/collectors/unix/main.go:362 +0x5ef\ngoharvest2/cmd/poller/schedule.(*task).Run(0xc00006ae40, 0x4b8f83cf0, 0xd236a0, 0x2540d6479)\n\tgoharvest2/cmd/poller/schedule/schedule.go:60 +0x56\ngoharvest2/cmd/poller/collector.(*AbstractCollector).Start(0xc00009a370, 0xc0001acfe0)\n\tgoharvest2/cmd/poller/collector/collector.go:269 +0x1b3\ncreated by main.(*Poller).Start\n\tcommand-line-arguments/poller.go:302 +0x225\n" Poller=unix1 collector=Unix:poller stack=[{"func":"New","line":"35","source":"errors.go"},{"func":"(*AbstractCollector).Start.func1","line":"240","source":"collector.go"},{"func":"gopanic","line":"965","source":"panic.go"},{"func":"goPanicIndex","line":"88","source":"panic.go"},{"func":"(*MetricUint8).SetValueUint8","line":"80","source":"metric_uint8.go"},{"func":"(*Matrix).LazySetValueUint8","line":"80","source":"lazy.go"},{"func":"(*Unix).PollData","line":"362","source":"main.go"},{"func":"(*task).Run","line":"60","source":"schedule.go"},{"func":"(*AbstractCollector).Start","line":"269","source":"collector.go"},{"func":"goexit","line":"1371","source":"asm_amd64.s"}]

</details>

### Steps to recreate

- copy/paste contents of shell script - save to file named `bug_rename_unix_collector`
- `chmod +x bug_rename_unix_collector`
- copy/paste contents of harvest config - save to file named `two.yml`
- `./bug_rename_unix_collector`

### Shell script to recreate

```
#!/bin/bash

HARVEST_YML=two.yml

# kill all pollers to start from a known state
pkill -9 -f "\-\-poller"
# reset name of xyc poller
sed -i "s/xyc.*-/xyc_1-/g" $HARVEST_YML

echo nothing should be running
bin/harvest --config $HARVEST_YML status

echo
echo start unix1
# Uncomment if you want more debug info - not needed to reproduce/verify
#bin/harvest --config $HARVEST_YML start unix1 --foreground &
bin/harvest --config $HARVEST_YML start unix1
pgrep -a -f "\-\-poller"

sleep 5s

echo start xyc_1-
bin/harvest --config $HARVEST_YML start xyc_1-
pgrep -a -f "\-\-poller"

# Rename running poller
sed -i "s/xyc.*-/xyc_$(date +'%s')-/g" $HARVEST_YML

echo renamed xyc

# After ~25s unix1 will die due to collector panic in unix.go

for _ in {1..20}
do
  pgrep -a -f "\-\-poller"
  if [ $? -eq 1 ]
  then
	  echo "BUG poller died"
	  exit 1
  fi
  sleep 2s
done


if pgrep -a -f "\-\-poller";
then
  echo "FIXED poller still running"
fi
```

### Harvest config to recreate

```
Exporters:
  prometheus:
    exporter: Prometheus
    addr: 0.0.0.0
    port: 12990

Pollers:
  unix1:
    datacenter: local
    collectors:
      - Unix
    exporters:
      - prometheus
  xyc_1623618968-:
    datacenter: local
    collectors:
      - Unix
```

**Comment by cgrinds** [comment]
Verified by starting 18 unix pollers, edited `harvest.yml` and removed all but one. Waited 10 minutes, no panics.
```
ubuntu     18988  0.7  1.4 1158912 14360 ?       Sl   22:24   0:06 bin/poller --poller unix --loglevel 2 --promPort 12990 --config h2.yml --daemon
ubuntu     19065  0.8  1.3 1158912 13352 ?       Sl   22:24   0:06 bin/poller --poller unix1 --loglevel 2 --promPort 2016 --config h2.yml --daemon
ubuntu     19083  0.7  1.3 1158912 13316 ?       Sl   22:24   0:05 bin/poller --poller unix2 --loglevel 2 --promPort 2010 --config h2.yml --daemon
ubuntu     19088  0.8  1.4 1158912 14360 ?       Sl   22:25   0:06 bin/poller --poller unix3 --loglevel 2 --promPort 2004 --config h2.yml --daemon
ubuntu     19094  0.7  1.4 1158912 14480 ?       Sl   22:25   0:06 bin/poller --poller unix4 --loglevel 2 --promPort 2012 --config h2.yml --daemon
ubuntu     19101  0.8  1.6 1232644 16476 ?       Sl   22:25   0:06 bin/poller --poller unix5 --loglevel 2 --promPort 2015 --config h2.yml --daemon
ubuntu     19126  0.7  1.5 1158912 16052 ?       Sl   22:25   0:06 bin/poller --poller unix6 --loglevel 2 --promPort 2007 --config h2.yml --daemon
ubuntu     19135  0.7  1.5 1158912 15804 ?       Sl   22:25   0:06 bin/poller --poller poll-4 --loglevel 2 --promPort 2018 --config h2.yml --daemon
ubuntu     19140  0.7  1.6 1158912 16188 ?       Sl   22:25   0:05 bin/poller --poller poll-5 --loglevel 2 --promPort 2013 --config h2.yml --daemon
ubuntu     19149  0.8  1.5 1158912 16020 ?       Sl   22:25   0:06 bin/poller --poller poll-6 --loglevel 2 --promPort 2026 --config h2.yml --daemon
ubuntu     19158  0.7  1.5 1158912 15956 ?       Sl   22:25   0:06 bin/poller --poller poll-7 --loglevel 2 --promPort 2027 --config h2.yml --daemon
ubuntu     19163  0.8  1.6 1158912 16208 ?       Sl   22:25   0:06 bin/poller --poller poll-8 --loglevel 2 --promPort 2002 --config h2.yml --daemon
ubuntu     19169  0.7  1.6 1158912 16088 ?       Sl   22:25   0:06 bin/poller --poller poll-9 --loglevel 2 --promPort 2008 --config h2.yml --daemon
ubuntu     19174  0.7  1.5 1158912 15932 ?       Sl   22:25   0:06 bin/poller --poller poll-10 --loglevel 2 --promPort 2014 --config h2.yml --daemon
ubuntu     19179  0.7  1.6 1158912 16252 ?       Sl   22:25   0:05 bin/poller --poller poll-12 --loglevel 2 --promPort 2030 --config h2.yml --daemon
ubuntu     19186  0.7  1.6 1158912 16348 ?       Sl   22:25   0:06 bin/poller --poller poll-13 --loglevel 2 --promPort 2009 --config h2.yml --daemon
ubuntu     19192  0.7  1.6 1158912 16412 ?       Sl   22:25   0:06 bin/poller --poller poll-14 --loglevel 2 --promPort 2022 --config h2.yml --daemon
ubuntu     19197  0.7  1.5 1158912 15868 ?       Sl   22:25   0:06 bin/poller --poller poll-15 --loglevel 2 --promPort 2003 --config h2.yml --daemon
```
