### ISSUE TITLE
WaflSizer RestPerf panics

### ISSUE THREAD

**Issue by rahulguptajss** [NetApp/harvest#2693]
Noticed during fsx testing

2024-02-20T12:48:55+05:30 ERR collector/collector.go:305 > Collector panicked runtime error: index out of range [33] with length 33 error="goroutine panic" Poller=fsx collector=RestPerf:WAFLSizer stack="goroutine 667 [running]:\ngithub.com/netapp/harvest/v2/pkg/logging.MarshalStack({0x10c8e8b60, 0xc000a2e080})\n\t/Users/rahulg2/GolandProjects/harvest/pkg/logging/logger.go:157 +0xad\ngithub.com/rs/zerolog.(*Event).Err(0xc000558000, {0x10c8e8b60, 0xc000a2e080})\n\t/Users/rahulg2/GolandProjects/harvest/vendor/github.com/rs/zerolog/event.go:395 +0xa2\ngithub.com/netapp/harvest/v2/cmd/poller/collector.(*AbstractCollector).Start.func1()\n\t/Users/rahulg2/GolandProjects/harvest/cmd/poller/collector/collector.go:304 +0xbf\npanic({0x10c8a4be0?, 0xc000413230?})\n\t/usr/local/opt/go/libexec/src/runtime/panic.go:770 +0x136\ngithub.com/netapp/harvest/v2/cmd/collectors/restperf.parseMetricResponses.func1.1.1({0x2, {0x0, 0x0}, {0x0, 0x0}, 0x3ff0000000000000, 0x0, {0x0, 0x0, 0x0}}, ...)\n\t/Users/rahulg2/GolandProjects/harvest/cmd/collectors/restperf/restperf.go:478 +0x6a6\ngithub.com/tidwall/gjson.Result.ForEach({0x5, {0xc001533c0e, 0x3a0e}, {0x0, 0x0}, 0x0, 0xfc0e, {0x0, 0x0, 0x0}}, ...)\n\t/Users/rahulg2/GolandProjects/harvest/vendor/github.com/tidwall/gjson/gjson.go:297 +0x8e5\ngithub.com/netapp/harvest/v2/cmd/collectors/restperf.parseMetricResponses.func1.1({0x2, {0x0, 0x0}, {0x0, 0x0}, 0x4045000000000000, 0x0, {0x0, 0x0, 0x0}}, ...)\n\t/Users/rahulg2/GolandProjects/harvest/cmd/collectors/restperf/restperf.go:472 +0xd08\ngithub.com/tidwall/gjson.Result.ForEach({0x5, {0xc0015241b4, 0x15086}, {0x0, 0x0}, 0x0, 0x1b4, {0x0, 0x0, 0x0}}, ...)\n\t/Users/rahulg2/GolandProjects/harvest/vendor/github.com/tidwall/gjson/gjson.go:297 +0x8e5\ngithub.com/netapp/harvest/v2/cmd/collectors/restperf.parseMetricResponses.func1({0x3, {0xc0015241a8, 0xa}, {0xc0015241a9, 0x8}, 0x0, 0x1a8, {0x0, 0x0, 0x0}}, ...)\n\t/Users/rahulg2/GolandProjects/harvest/cmd/collectors/restperf/restperf.go:434 +0x305\ngithub.com/tidwall/gjson.Result.ForEach({0x5, {0xc001524015, 0x1522b}, {0x0, 0x0}, 0x0, 0x15, {0x0, 0x0, 0x0}}, ...)\n\t/Users/rahulg2/GolandProjects/harvest/vendor/github.com/tidwall/gjson/gjson.go:297 +0x8e5\ngithub.com/netapp/harvest/v2/cmd/collectors/restperf.parseMetricResponses({0x5, {0xc001524015, 0x1522b}, {0x0, 0x0}, 0x0, 0x15, {0x0, 0x0, 0x0}}, ...)\n\t/Users/rahulg2/GolandProjects/harvest/cmd/collectors/restperf/restperf.go:431 +0x1d1\ngithub.com/netapp/harvest/v2/cmd/collectors/restperf.(*RestPerf).pollData.func1({0x2, {0x0, 0x0}, {0x0, 0x0}, 0x0, 0x0, {0x0, 0x0, 0x0}}, ...)\n\t/Users/rahulg2/GolandProjects/harvest/cmd/collectors/restperf/restperf.go:847 +0x1205\ngithub.com/tidwall/gjson.Result.ForEach({0x5, {0xc00152400f, 0x3efbd}, {0x0, 0x0}, 0x0, 0xf, {0x0, 0x0, 0x0}}, ...)\n\t/Users/rahulg2/GolandProjects/harvest/vendor/github.com/tidwall/gjson/gjson.go:297 +0x8e5\ngithub.com/netapp/harvest/v2/cmd/collectors/restperf.(*RestPerf).pollData(0xc000424cb0, {0xc16d3277e7ed3cb8, 0x1c27c23252, 0x10ccf7320}, {0xc000f92060, 0x1, 0x1})\n\t/Users/rahulg2/GolandProjects/harvest/cmd/collectors/restperf/restperf.go:730 +0x6d2\ngithub.com/netapp/harvest/v2/cmd/collectors/restperf.(*RestPerf).PollData(0xc000424cb0)\n\t/Users/rahulg2/GolandProjects/harvest/cmd/collectors/restperf/restperf.go:687 +0x512\ngithub.com/netapp/harvest/v2/cmd/poller/schedule.(*Task).Run(0xc0007aa230)\n\t/Users/rahulg2/GolandProjects/harvest/cmd/poller/schedule/schedule.go:60 +0x4f\ngithub.com/netapp/harvest/v2/cmd/poller/collector.(*AbstractCollector).Start(0xc0006c6b60, 0xc0007f8880)\n\t/Users/rahulg2/GolandProjects/harvest/cmd/poller/collector/collector.go:348 +0x3f0\ncreated by main.(*Poller).Start in goroutine 1\n\t/Users/rahulg2/GolandProjects/harvest/cmd/poller/poller.go:414 +0x2dc\n"

**Comment by cgrinds** [comment]
Sample JSON [response](https://github.com/NetApp/harvest/files/14345591/sample.json).
