### ISSUE TITLE
cluster svm_labels missing

### ISSUE THREAD

**Issue by WayneShen2** [NetApp/harvest#3122]
**Is your feature request related to a problem? Please describe.**
I could see our 1 cluster 
![volume_lables](https://github.com/user-attachments/assets/8947e1fa-5a89-44c8-bf6f-f62541faeae5)
svm_labels missing

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
![Uploading volume_lables.png…]()

**Comment by WayneShen2** [comment]
i could see log error log.

2024-08-27T00:23:17Z ERR collector/collector.go:308 > Collector panicked runtime error: invalid memory address or nil pointer dereference error="goroutine panic" Poller=bocfs10 collector=ZapiPerf:FlexCache stack="goroutine 803 [running]:\ngithub.com/netapp/harvest/v2/pkg/logging.MarshalStack({0xc60060?, 0xc007ef6680?})\n\tgithub.com/netapp/harvest/v2/pkg/logging/logger.go:157 +0x85\ngithub.com/rs/zerolog.(*Event).Err(0xc0001a9960, {0xc60060, 0xc007ef6680})\n\tgithub.com/rs/zerolog@v1.33.0/event.go:395 +0x51\ngithub.com/netapp/harvest/v2/cmd/poller/collector.(*AbstractCollector).Start.func1()\n\tgithub.com/netapp/harvest/v2/cmd/poller/collector/collector.go:307 +0xc7\npanic({0xa9f4c0?, 0x1090c80?})\n\truntime/panic.go:770 +0x132\ngithub.com/netapp/harvest/v2/pkg/set.(*Set).Has(...)\n\tgithub.com/netapp/harvest/v2/pkg/set/set.go:39\ngithub.com/netapp/harvest/v2/cmd/collectors/zapiperf/plugins/flexcache.(*FlexCache).Run(0xc0001b0ad0, 0xc0007ae300?)\n\tgithub.com/netapp/harvest/v2/cmd/collectors/zapiperf/plugins/flexcache/flexcache.go:61 +0x178\ngithub.com/netapp/harvest/v2/cmd/poller/collector.(*AbstractCollector).Start(0xc0003248f0, 0x0?)\n\tgithub.com/netapp/harvest/v2/cmd/poller/collector/collector.go:452 +0x17e7\ncreated by main.(*Poller).Start in goroutine 1\n\tgithub.com/netapp/harvest/v2/cmd/poller/poller.go:485 +0x85\n"
2
